export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const SIGNUP='SIGNUP';
export const SIGNIN='SIGNIN';
export const FETCH_RESTAURANTS_BY_ID ='FETCH_RESTAURANTS_BY_ID';
export const FETCH_MENU_ITEMS_BY_ID ='FETCH_MENU_ITEMS_BY_ID';
